apiVersion: v1
kind: Service
metadata:
  name: devopsforge-api
  namespace: devopsforge
  labels:
    app: devopsforge-api
spec:
  type: LoadBalancer
  selector:
    app: devopsforge-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
